easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\User
        - App\Entity\Role
        - App\Entity\Question
        - App\Entity\Response
        - App\Entity\Coeff
        - App\Entity\Theme
        - App\Entity\Step
        - App\Entity\Level
        - App\Entity\Joker
        - App\Entity\Home
        - App\Entity\JokerQuantity
