lexik_jwt_authentication:
    secret_key:       '%kernel.root_dir%/../var/jwt/private.pem' # required for token creation
    public_key:       '%kernel.root_dir%/../var/jwt/public.pem'  # required for token verification
    pass_phrase:      'bravo' # required for token creation, usage of an environment variable is recommended
    token_ttl:        3600